### ISSUE TITLE
How to deal with Viewpager? 

### ISSUE THREAD

**Issue by Rainer-Lang** [grandcentrix/ThirtyInch#16]
I use a viewpager
a) to show data in RecyclerViews
b) to create a new object
and I'm interested how to use it with your lib.

**Comment by passsy** [comment]
ThirtyInch doesn't define how you structure your UI implementation. `ViewPager` works as well but your Activity (the `TiView` implementation) is responsible to forward the data to the corresponding pages inside the `ViewPager`. The presenter doesn't know about the `ViewPager`, it only knowns the `TiView` has multiple lists which have to be filled with data.

It's hard to guess how you are using the ViewPager right now. Here some suggestions:

You can use a `ViewPager` with fragments inside. Each `Fragment` can have it's own presenter. This is useful when one tab is totally independent from the others. 

We recently had a UI with two tabs showing different lists. We used a `ViewPager` to switch between them. Instead of a `ViewPager` with fragments we used plain views (`RecyclerView`) and filled the data in those adapters from the presenter.

**Comment by Rainer-Lang** [comment]
I'm using the ViewPager with fragments.

1)
I have ViewPagers with fragments inside which have ReceyclerViews. Data is loaded from database. User could interact with RecyclerView-items (mark favorite, open items,...).
The RecyclerView-items (items look nearly same and also the functionality is nearly the same (items have state "running"/"finished", therefore different interactions)).

2)
And I also have ViewPager to create an item. This means every fragment is completely different - but at the sum all data of the fragments is ONE object which will be created. I have to validate the input data (not only for one fragment but for all fragments together).

**Comment by Rainer-Lang** [comment]
@passsy Should I provide more information? What do you need? I'm very interested in using this lib.

**Comment by passsy** [comment]
There is no "right" way to implement MVP with ThirtyInch when your UI has a `ViewPager`. It's totally up to you.

You can put presenters in the fragments of the ViewPager, you can put a single presenter in the Activity. I've seen and implemented all of those scenarios. All have pros and cons and you have to decide what fits best into your app architecture and personal preference.

First of all you should ask yourself what kind of problem you are trying to solve with the introduction of MVP. That's why I can't answer your questions. I have no idea what stops you from using `Ti`.
If you don't have a problem you should not use `Ti`.

**Comment by Rainer-Lang** [comment]
One last question in this thread (thanks for your time):
> You can put presenters in the fragments of the ViewPager, you can put a single presenter in the Activity. I've seen and implemented all of those scenarios. All have pros and cons and you have to decide what fits best into your app architecture and personal preference.

And all scenarios are working with ```Ti```?

**Comment by passsy** [comment]
yes, there is `TiActivity` and `TiFragment`
